# Etapa 1: Construcción de la aplicación Angular
FROM node:16-alpine AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de los archivos de la aplicación
COPY . .

# Construir la aplicación para producción
RUN npm run build -- --prod

# Etapa 2: Servir la aplicación con un servidor web
FROM nginx:stable-alpine

# Copiar los archivos compilados de la etapa de construcción
COPY --from=build /app/dist/tu-aplicacion-angular /usr/share/nginx/html

# Copiar el archivo de configuración de NGINX
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto 80 para el contenedor
EXPOSE 80

# Comando para iniciar NGINX
CMD ["nginx", "-g", "daemon off;"]